#!/bin/sh

if rpm -q nodejs
then
    echo "nodejs installed"
else
    curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
    yum install -y nodejs
fi

if rpm -q supervisor
then
    echo "supervisor installed"
else
    yum install -y supervisor
    systemctl start supervisord
    systemctl enable supervisord
fi

rsync -avz -t ./hook.ini /etc/supervisord.d/hook.ini

systemctl restart supervisord
