#!/bin/sh

if rpm -q supervisor
then
    echo "supervisor installed"
else
    yum install -y supervisor
    systemctl start supervisord
    systemctl enable supervisord
fi

rsync -avz -t ./hook.ini /etc/supervisord.d/hook.ini

systemctl restart supervisord
